version: '2.1'
volumes:
    cloudblockdata: {}
services:
    sensor:
        build: sensor
        privileged: true
        tty: true
        restart: always
        network_mode: host
        volumes:
            - 'cloudblockdata:/data'
        depends_on: 
            - "mqtt"
    mqtt:
        image: eclipse-mosquitto@sha256:52d0254fc54bea116ceb5fc066331ba82ed2ae4b66e2cc238a90f708439b32d7
        # pinned to this release and NUC arch
        ports:
            - "1883:1883"
        restart: always
    input:
        build: input
        restart: always
        network_mode: host
        privileged: true
        depends_on: 
            - "mqtt"
            - "sensor"