version: '2.1'
services:
    data_relay:
        # Local build in data_relay directory required only for MS Azure Key Vault,
        # secret store to copy in certificate file. Otherwise OK to use image.
        #build: data_relay
        image: kb2ma/data-relay
        privileged: true
        tty: true
        restart: always
        network_mode: host
        depends_on: 
            - "mqtt"
    mqtt:
        image: eclipse-mosquitto:1.6.14
        ports:
            - "1883:1883"
        restart: always
    data_source:
        build: cputemp
        privileged: true
        restart: always
        depends_on:
            - "mqtt"
