version: '2.1'
services:
    data_relay:
        image: balenablocks/data-relay
        privileged: true
        tty: true
        restart: always
        network_mode: host
        depends_on: 
            - "mqtt"
    mqtt:
        image: eclipse-mosquitto:1.6.14
        ports:
            - "1883:1883"
        restart: always
    data_source:
        build: cputemp
        privileged: true
        restart: always
        depends_on:
            - "mqtt"
